### ISSUE TITLE
Yahoo suddenly terminated its finance API which is used in this book?

### ISSUE THREAD

**Issue by singhlaanshul** [PacktPublishing/-Reactive-Android-Programming#1]
check details here : https://yahoo.sdx.socialdynamx.com/portal/conversation/19248672

It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com .

Thanks

**Comment by lokinmodar** [comment]
yeah, i noticed something wrong too. Since RxJava 2.x no longer accepts null values and will yield NullPointerException, we need some update in the codes at least or a different API to target.... the apps will always crash when run because of this error...

**Comment by thebatu** [comment]
Any code update to resolve this issue ?

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue. If the issue still persists, feel free to reopen it.
Thanks!
